### ISSUE TITLE
Why not use git bare repository

### ISSUE THREAD

**Issue by LCRERGO** [luissimas/dotfiles#1]
Hi, I wanted to know why not use git bare repositories instead of GNU Stow to manage your dotfiles

**Comment by luissimas** [comment]
No particular strong reason. I used to manage my dotfiles using a git bare repository. I actually used this approach for quite some time, but then moved to a stow-based approach mostly for two (personal) reasons:

1. I don't like the idea of my entire home directory being a git repository, with stow I feel that can keep my dotfiles more contained inside a separated folder. This allows me to have some setup scripts and auxiliar files on the root of my dotfiles without the need to have them in the root of my home folder.
2. With GNU stow I can choose which folders I want to symlink. This means that I can choose to install my configuration for only certain tools, and it makes a bit easier to manage modules individually.

**Comment by LCRERGO** [comment]
I understood.
